WeatherPattern = {
    [1] =  {["number"] = 1,  ["type"]= "Sunny"},
    [2] =  {["number"] = 2,  ["type"]= "Clouds"},
    [3] =  {["number"] = 3,  ["type"]= "Overcast"},
    [4] =  {["number"] = 4,  ["type"]= "Drizzle"},
    [5] =  {["number"] = 5,  ["type"]= "OvercastDark"},
    [6] =  {["number"] = 6,  ["type"]= "Thunder"},
    [7] =  {["number"] = 7,  ["type"]= "Thunderstorm"},
    [8] =  {["number"] = 8,  ["type"]= "Rain"},
    [9] =  {["number"] = 9,  ["type"]= "Shower"},
    [10] = {["number"] = 10, ["type"]= "Overcast"},
    [11] = {["number"] = 11, ["type"]= "Clouds"},
    [12] = {["number"] = 12, ["type"]= "Sunny"},
    [13] = {["number"] = 13, ["type"]= "Sunny"},
    [14] = {["number"] = 14, ["type"]= "Sunny"},
    [15] = {["number"] = 15, ["type"]= "Clouds"},
    [16] = {["number"] = 16, ["type"]= "Drizzle"},
    [17] = {["number"] = 17, ["type"]= "Clouds"},
    [18] = {["number"] = 18, ["type"]= "Fog"},
    [19] = {["number"] = 19, ["type"]= "Sunny"},
    [20] = {["number"] = 20, ["type"]= "Sunny"},
    [21] = {["number"] = 21, ["type"]= "Sunny"},
    [22] = {["number"] = 22, ["type"]= "Sunny"},
}
